server:
  port: 8080

spring:
  application:
    name: eatngo-customer-api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

swagger:
  title: "EatNGo 사용자 API"
  description: "EatNGo 서비스의 사용자용 API 문서"
  version: "v1.0.0"