server:
  port: 8081

spring:
  application:
    name: eatngo-store-owner-api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

swagger:
  title: "EatNGo 점주 API"
  description: "EatNGo 서비스의 점주용 API 문서"
  version: "v1.0.0"