server:
  port: 8080
  forward-headers-strategy: framework
spring:
  config:
    import:
      - classpath:auth-application.yml
      - classpath:auth-application-prod.yml
      - classpath:application-metrics.yml
      - aws-parameterstore:/eatngo/
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
  application:
    name: eatngo-store-owner-api
  datasource:
    url: ${PG_URL}
    username: eatngo_admin
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: eatngo-app

datastore:
  mongodb:
    uri: ${MONGO_URI}
    database: eatngo
    username: eatngo-dev
    password: ${MONGO_PW}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

swagger:
  title: "EatNGo 점주 API"
  description: "EatNGo 서비스의 점주용 API 문서"
  version: "v1.0.0"

logging:
  level:
    org.hibernate.SQL: warn