version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: eatngo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eatngo
      POSTGRES_USER: eatngo_user
      POSTGRES_PASSWORD: eatngolocal
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

 # TODO : Atlas 연결 or 로컬에서도 검색 동작하도록 수정
  mongodb:
    image: mongo:8
    container_name: eatngo-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eatngo
      MONGO_INITDB_ROOT_USERNAME: eatngo-owner
      MONGO_INITDB_ROOT_PASSWORD: eatngolocal
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7.2.4
    container_name: eatngo-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass eatngolocal
    volumes:
        - redis_data:/data
    restart: unless-stopped

  customer-api:
    build:
      context: ../../eatngo-customer-api
      dockerfile: Dockerfile
    container_name: eatngo-customer-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
      - redis
    restart: unless-stopped

  store-owner-api:
    build:
      context: ../../eatngo-store-owner-api
      dockerfile: Dockerfile
    container_name: store-owner-api
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - mongodb
      - redis
    restart: unless-stopped

volumes:
  pg_data:
  mongo_data:
  redis_data: