groups:
  - name: circuit_breaker_alerts
    rules:
      # Circuit Breaker가 OPEN 상태인 경우
      - alert: CircuitBreakerOpen
        expr: circuit_breaker_state == 1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Circuit Breaker {{ $labels.name }}이 OPEN 상태입니다"
          description: "Redis Circuit Breaker {{ $labels.name }}이 30초 이상 OPEN 상태입니다. Fallback 모드로 동작 중"

      # Circuit Breaker 실패율이 높은 경우
      - alert: CircuitBreakerHighFailureRate
        expr: |
          (
            rate(circuit_breaker_calls{result="failure"}[5m]) /
            rate(circuit_breaker_calls[5m])
          ) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Circuit Breaker {{ $labels.name }} 실패율이 높습니다"
          description: "Circuit Breaker {{ $labels.name }}의 실패율이 50%를 초과했습니다 (5분간)"

      # Circuit Breaker 응답시간이 느린 경우
      - alert: CircuitBreakerSlowResponse
        expr: histogram_quantile(0.95, rate(circuit_breaker_calls_duration_bucket[5m])) > 5
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Circuit Breaker {{ $labels.name }} 응답시간이 느립니다"
          description: "Circuit Breaker {{ $labels.name }}의 95% 응답시간이 5초를 초과했습니다"

      # Fallback 실행이 많은 경우
      - alert: CircuitBreakerHighFallbackRate
        expr: rate(circuit_breaker_fallbacks[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Circuit Breaker {{ $labels.name }} Fallback 실행이 빈번합니다"
          description: "Circuit Breaker {{ $labels.name }}에서 분당 10회 이상 Fallback이 실행되고 있습니다"

      # Circuit Breaker 상태 변화가 빈번한 경우
      - alert: CircuitBreakerFrequentStateChanges
        expr: rate(circuit_breaker_state_transitions[10m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Circuit Breaker {{ $labels.name }} 상태 변화가 빈번합니다"
          description: "Circuit Breaker {{ $labels.name }}이 10분간 5회 이상 상태가 변경되었습니다. 서비스 불안정 가능성" 