name: CI

# 푸시 또는 PR 발생 시 실행
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Gradle Tests
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설치 및 Gradle 캐시 설정
      - name: Set up JDK 17 and cache Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 3. gradlew 스크립트 실행 권한 부여 (windows-hosted 환경이 아니라면 생략 가능)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 의존성 다운로드 및 테스트 실행
      - name: Run tests
        run: ./gradlew clean test --no-daemon

      # 5. (선택) 테스트 결과 업로드
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            **/build/test-results/**/*.xml
            **/build/reports/tests/**/*.html
