name: CI

# 푸시 또는 PR 발생 시 실행
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Gradle Tests
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설치 및 Gradle 캐시 설정
      - name: Set up JDK 21 and cache Gradle
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # 3. gradlew 스크립트 실행 권한 부여 (windows-hosted 환경이 아니라면 생략 가능)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. eatngo-common 모듈 클린 빌드
      # eatngo-infra가 의존하는 eatngo-common 모듈을 먼저 빌드
      - name: Clean build eatngo-common module
        run: ./gradlew :eatngo-common:clean :eatngo-common:build --no-daemon

      # 5. 모든 모듈을 다시 빌드하고 테스트를 실행합니다.
      # 강제 새로고침 수행
      - name: Run clean build for entire project with dependency refresh
        run: ./gradlew clean build --no-daemon --refresh-dependencies